//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attendanceWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class verfication
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> data { get; set; }
        public int done { get; set; }
    }
}
